<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://pucminas.br/SN/CreditoService/RenatoRibeiro"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:cre="http://pucminas.br/SN/CreditoGeral"
	xmlns:cab="http://pucminas.br/MC/SOA/RenatoRibeiro" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="CreditoGeralService" targetNamespace="http://pucminas.br/SN/CreditoService/RenatoRibeiro">

	<wsdl:types>
		<xsd:schema targetNamespace="http://pucminas.br/SN/CreditoService/RenatoRibeiro">
			<xsd:import namespace="http://pucminas.br/SN/CreditoGeral" schemaLocation="../xsd/ParametrosCreditoGeral.xsd" />
			<xsd:import namespace="http://pucminas.br/MC/SOA/RenatoRibeiro" schemaLocation="../../../ModeloCanonico/MC/PucminasFault.xsd" />
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="pucminasFault">
		<wsdl:part element="cab:pucminasFault" name="fault" />
	</wsdl:message>

	<wsdl:message name="verificaCreditoGeralRequest">
		<wsdl:part element="cre:parametrosVerificaCreditoGeral"
			name="parameters" />
	</wsdl:message>
	<wsdl:message name="verificaCreditoGeralResponse">
		<wsdl:part element="cre:resultadoVerificaCreditoGeral" name="parameters" />
	</wsdl:message>

	<wsdl:portType name="CreditoGeralService">
		<wsdl:operation name="verificaCreditoGeral">
			<wsdl:input message="tns:verificaCreditoGeralRequest" />
			<wsdl:output message="tns:verificaCreditoGeralResponse" />
			<wsdl:fault name="pucminasFault" message="tns:pucminasFault" />
		</wsdl:operation>
	</wsdl:portType>


	<wsdl:binding name="CreditoGeralServiceSOAP" type="tns:CreditoGeralService">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="verificaCreditoGeral">
			<soap:operation
				soapAction="http://pucminas.br/SN/CreditoGeral/VerificaCreditoGeral" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="pucminasFault">
				<soap:fault name="pucminasFault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="CreditoGeralService">
		<wsdl:port binding="tns:CreditoGeralServiceSOAP" name="CreditoGeralServiceSOAP">
			<soap:address location="http://pucminas.br/SOA/Credito" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
